package JTAG_TB;

import StmtFSM :: *;

import JTAG_Types :: *;
import JTAG_TB_Stmt :: *;

function Bit#(sw) jtag_capture_mask(Integer first_bit_delay, Integer data_bits);
    Bit#(sw) mask = 0;
    for(Integer bit_index = 0; bit_index < valueof(sw); bit_index = bit_index + 1) begin
        Integer out_index = bit_index + 1 - first_bit_delay;
        if(out_index >= 0 && out_index < data_bits) begin
            mask[valueof(sw) - 1 - bit_index] = 1;
        end
    end
    return mask;
endfunction

function Stmt jtag_stim(
    Wire#(Bit#(1)) tck,
    Wire#(Bit#(1)) tms,
    Wire#(Bit#(1)) tdi,
    Bit#(1)        tms_v,
    Bit#(1)        tdi_v
);
    return seq
        action
            tck <= 0;
            tms <= tms_v;
            tdi <= tdi_v;
        endaction
        action
            tck <= 1;
            tms <= tms_v;
            tdi <= tdi_v;
        endaction
    endseq;
endfunction

function Stmt jtag_sequence(
    Wire#(Bit#(1)) tck,
    Wire#(Bit#(1)) tms,
    Wire#(Bit#(1)) tdi,
    Bit#(w)        tms_vec,
    Bit#(w)        tdi_vec
);
    return jtag_sequence_hidden(tck, tms, tdi, tms_vec, tdi_vec);
endfunction

function Stmt jtag_idle(
    Wire#(Bit#(1)) tck,
    Wire#(Bit#(1)) tms,
    Wire#(Bit#(1)) tdi,
    Integer        cycles
);
    return seq
        repeat(fromInteger(cycles)) seq
            jtag_stim(tck, tms, tdi, 0, 0);
        endseq
    endseq;
endfunction

function Stmt jtag_reset(
    Wire#(Bit#(1)) tck,
    Wire#(Bit#(1)) tms,
    Wire#(Bit#(1)) tdi
);
    // JTAG FSM reset: Hold TMS high for 5 TCK cycles, then go to Run-Test/Idle with TMS=0
    return jtag_sequence(tck, tms, tdi, 6'b111110, 6'b0);
endfunction

function Stmt jtag_ir(
    Wire#(Bit#(1))        tck,
    Wire#(Bit#(1))        tms,
    Wire#(Bit#(1))        tdi,
    JTAGInstruction_t#(w) instr
)
    provisos(
        Add#(w1, 1, w)
    );
    //go to Shift-IR state with 1100
    //then repeat shift w times
    //then go to Run-Test/Idle with 110
    Bit#(w1) z = 0;
    Bit#(TAdd#(w, 6)) tms_v = {4'b1100, z, 3'b110};
    Bit#(TAdd#(w, 6)) tdi_v = {4'b0000, reverseBits(instr), 2'b00};
    return jtag_sequence(tck, tms, tdi, tms_v, tdi_v);
endfunction

function Stmt jtag_sequence_ret(
    Wire#(Bit#(1)) tck,
    Wire#(Bit#(1)) tms,
    Wire#(Bit#(1)) tdi,
    Wire#(Bit#(1)) tdo,
    Bit#(sw)       tms_vec,
    Bit#(sw)       tdi_vec,
    Bit#(sw)       capture_vec,
    Reg#(Bit#(w))  out
)
    provisos(
        Add#(w1, 1, w)
    );
    return jtag_sequence_ret_hidden(tck, tms, tdi, tdo, tms_vec, tdi_vec, capture_vec, out);
endfunction

function Stmt jtag_dr_ret_del(
    Wire#(Bit#(1)) tck,
    Wire#(Bit#(1)) tms,
    Wire#(Bit#(1)) tdi,
    Wire#(Bit#(1)) tdo,
    Bit#(w)        inp,
    Reg#(Bit#(w))  out,
    Integer        tdo_delay
)
    provisos(
        Add#(w1, 1, w)
    );
    Bit#(w1) z = 0;
    Bit#(TAdd#(w, 6)) tms_v = {4'b100, z, 3'b110};
    Bit#(TAdd#(w, 6)) tdi_v = {4'b000, reverseBits(inp), 2'b00};
    /* TCK is generated by the testbench functions with half the speed of the FSM clock.
    TCK is set to 0 in FSM cycle 0 and set to 1 in FSM cycle 1. During that time, TMS and TDI
    are applied simultaneously. The bluespec clock generated from the TCK wire is inverted wrt. the wire
    because it is driven by a register.
    We expect the TAP to be in RunTestIdle, whenever a command sequence is applied and thus it takes the
    three TMS 0b100 to reach ShiftDR.
    */
    Integer first_bit_delay = (5 + tdo_delay);
    Bit#(TAdd#(w, 6)) capture_v = jtag_capture_mask(first_bit_delay, valueof(w));
    return jtag_sequence_ret(tck, tms, tdi, tdo, tms_v, tdi_v, capture_v, out);
endfunction

function Stmt jtag_dr_ret(
    Wire#(Bit#(1)) tck,
    Wire#(Bit#(1)) tms,
    Wire#(Bit#(1)) tdi,
    Wire#(Bit#(1)) tdo,
    Bit#(w)        inp,
    Reg#(Bit#(w))  out
)
    provisos(
        Add#(w1, 1, w)
    )
    = jtag_dr_ret_del(tck, tms, tdi, tdo, inp, out, 0);

function Stmt jtag_dr(
    Wire#(Bit#(1)) tck,
    Wire#(Bit#(1)) tms,
    Wire#(Bit#(1)) tdi,
    Bit#(w)        inp
)
    provisos(
        Add#(w1, 1, w)
    );
    Bit#(w1) z = 0;
    Bit#(TAdd#(w, 6)) tms_v = {4'b100, z, 3'b110};
    Bit#(TAdd#(w, 6)) tdi_v = {4'b000, reverseBits(inp), 2'b00};
    return jtag_sequence(tck, tms, tdi, tms_v, tdi_v);
endfunction

endpackage
