`define SCOOOTER_CONFIG_ONLY
`include "ScoooterCpu.bsv"
`undef SCOOOTER_CONFIG_ONLY

package Config;

// SCOoOTER expects these settings in a package named Config.
typedef `SCOOOTER_CFG_IFU_INST IFUINST;
typedef `SCOOOTER_CFG_ISSUE_WIDTH ISSUEWIDTH;

typedef `SCOOOTER_CFG_RESET_VECTOR RESETVEC;

typedef `SCOOOTER_CFG_BASE_IMEM BASE_IMEM;
typedef `SCOOOTER_CFG_SIZE_IMEM SIZE_IMEM;
typedef `SCOOOTER_CFG_BASE_DMEM BASE_DMEM;
typedef `SCOOOTER_CFG_SIZE_DMEM SIZE_DMEM;

typedef `SCOOOTER_CFG_ROB_BANK_DEPTH ROB_BANK_DEPTH;
typedef `SCOOOTER_CFG_INST_WINDOW INST_WINDOW;
typedef `SCOOOTER_CFG_MUL_DIV_STRATEGY MUL_DIV_STRATEGY;

typedef `SCOOOTER_CFG_NUM_ALU NUM_ALU;
typedef `SCOOOTER_CFG_NUM_MUL_DIV NUM_MULDIV;
typedef `SCOOOTER_CFG_NUM_BRANCH NUM_BR;

typedef 0 REGFILE_LATCH_BASED;
typedef 0 REGEVO_LATCH_BASED;
typedef 0 REGCSR_LATCH_BASED;

typedef `SCOOOTER_CFG_RS_DEPTH_ALU RS_DEPTH_ALU;
typedef `SCOOOTER_CFG_RS_DEPTH_MEM RS_DEPTH_MEM;
typedef `SCOOOTER_CFG_RS_DEPTH_CSR RS_DEPTH_CSR;
typedef `SCOOOTER_CFG_RS_DEPTH_MUL_DIV RS_DEPTH_MULDIV;
typedef `SCOOOTER_CFG_RS_DEPTH_BRANCH RS_DEPTH_BR;

typedef `SCOOOTER_CFG_STORE_BUFFER_DEPTH STORE_BUF_DEPTH;

typedef `SCOOOTER_CFG_BRANCH_PREDICTOR BRANCHPRED;
typedef `SCOOOTER_CFG_BTB_INDEX_BITS BITS_BTB;
typedef `SCOOOTER_CFG_PHT_INDEX_BITS BITS_PHT;
typedef `SCOOOTER_CFG_BRANCH_HISTORY_BITS BITS_BHR;

typedef 1 USE_RAS;
typedef 0 RAS_SAVE_HEAD;
typedef 0 RAS_SAVE_FIRST;
typedef 2 RASDEPTH;

`ifdef SCOOOTER_NUM_THREADS
typedef `SCOOOTER_NUM_THREADS NUM_THREADS;
`else
typedef 1 NUM_THREADS;
`endif

`ifdef SCOOOTER_NUM_CPU
typedef `SCOOOTER_NUM_CPU NUM_CPU;
`else
typedef 1 NUM_CPU;
`endif

typedef 0 DECODE_LATCH_OUTPUT;
typedef 0 ROB_LATCH_OUTPUT;
typedef 0 RESBUS_ADDED_DELAY;
typedef 0 RS_LATCH_INPUT;
typedef 0 SPLIT_ISSUE_STAGE;

endpackage
